sudo: false
language: node_js
node_js:
- '6.2'
notifications:
    email: false
branches:
  only:
    - master
services:
  - docker
env:
   global:
     - DOCKER_CONTAINER=local-dynamo
cache:
  directories:
    - node_modules
before_script:
  - npm install --ignore-scripts
  - npm prune
script:
  - npm test
  - npm run build
  - node ./integration-tests/runner.js
  - npm run test:integration
  - node ./integration-tests/saver.js
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_AUTH_TOKEN
  on:
    branch: master
