sudo: false
language: node_js
node_js:
- '6.2'
notifications:
    email: false
branches:
  only:
    - master
services:
  - docker
env:
   global:
     - DOCKER_CONTAINER=local-dynamo
cache:
  directories:
    - node_modules
before_script:
  - npm install
  - npm prune
script:
  - npm test
  - sh ./deploy/seed-integration-test-data.sh
  - npm run test:integration
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_AUTH_TOKEN
  on:
    branch: master
